spring:
  application:
    name: api-gateway
  config:
    import: "configserver:http://10.160.0.42:8888"

#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#
#      routes:
#
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path=/api/v1/users/**